document.write("<div class="main">");
document.write("<div class="topnav">");
document.write("<a href="https://www.geometryexplorer.xyz">Exploring Euclidean Geometry</a>");
document.write("<a href="/texfiles/CV/cv.pdf">CV</a>");
document.write("<div class="topnav-right">");
document.write("<a href="/essay">Essays</a>");
document.write("<a href="/handouts">Handouts</a>");
document.write("<a href="https://mast.geometryexplorer.xyz/">MAST</a>");
document.write("</div>");
document.write("</div>");