document.write("<div class=\"main\">");
document.write("<div class=\"topnav\">");
document.write("<a href=\"https:\/\/www.geometryexplorer.xyz\">Home<\/a>");
document.write("<a href=\"\/texfiles\/CV\/cv.pdf\">CV<\/a>");
document.write("<a href=\"\/socials\">Socials<\/a>");
document.write("<a href=\"\/essay\">Essays</a>");
document.write("<a href=\"\/handouts\">Handouts<\/a>");
document.write("<div class=\"topnav-right\">");
document.write("<a href=\"https:\/\/mast.geometryexplorer.xyz\/\">MAST<\/a>");
document.write("<a href=\"https:\/\/mat.mathadvance.org\/\">MAC<\/a>");
document.write("<\/div>");
document.write("<\/div>");
