if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-32";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

//Generated By AsyPadv1.2
import olympiad;
import markers;
import math;
import graph;
//change the unit size to fit your needs
size(3cm);
//colored pens
pen c000000 = rgb("000000");
//dependency level 0
/* You can change the coordinates of these points of dependency level 0.
The drawing will retain the same relationships and qualities.
Please be aware that as a result of this some of the image may be clipped off. */
pair A = (3.32, 17.11); dot(A, c000000); label("$A$", A, dir(207.8972710309471));
pair B = (5.05, 17.09); dot(B, c000000); label("$B$", B, dir(325.00797980144));
//dependency level 1
//Do not change anything below, unless you are experienced in Asymptote.
path pbA_B = ((A+B)/2-20.0*unit(((B-A).y, -(B-A).x)))--((A+B)/2+20.0*unit(((B-A).y, -(B-A).x)));
path segA_B = A--B; draw(segA_B, c000000);
//dependency level 2
pair C = relpoint(pbA_B, 0.5134646278119219); dot(C, c000000); label("$C$", C, dir(274.31287501714553));
pair P = intersectionpoint(pbA_B, segA_B); dot(P, c000000); label("$P$", P, dir(50.95410743116071));
//dependency level 3
path ccA_C_B = circumcircle(A, C, B);
pair ccA_C_Bcenter = circumcenter(A, C, B); real ccA_C_Brad = circumradius(A, C, B); draw(ccA_C_B, c000000);
//dependency level 4
pair D = intersectionpoints(pbA_B, ccA_C_B)[0]; dot(D, c000000); label("$D$", D, dir(88.75312672365999));
//dependency level 5
path segD_C = D--C; draw(segD_C, c000000);
