if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-30";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

//Generated By AsyPadv1.2
import olympiad;
import markers;
import math;
import graph;
//change the unit size to fit your needs
size(4cm);
//colored pens
pen c000000 = rgb("000000");
//dependency level 0
/* You can change the coordinates of these points of dependency level 0.
The drawing will retain the same relationships and qualities.
Please be aware that as a result of this some of the image may be clipped off. */
pair A = (3.47, 17.85); dot(A, c000000); label("$A$", A, dir(126.02737338510292));
pair B = (2.88, 16.31); dot(B, c000000); label("$B$", B, dir(236.09372301155847));
pair C = (4.64, 16.25); dot(C, c000000); label("$C$", C, dir(319.3987053549977));
//dependency level 1
//Do not change anything below, unless you are experienced in Asymptote.
path ccA_B_C = circumcircle(A, B, C);
pair ccA_B_Ccenter = circumcenter(A, B, C); real ccA_B_Crad = circumradius(A, B, C); draw(ccA_B_C, c000000);
path lineB_A = (B-20.0*unit(A-B))--(A+20.0*unit(A-B));
//dependency level 2
pair D = relpoint(ccA_B_C, 0.21889966793444027); dot(D, c000000); label("$D$", D, dir(48.14541204060811));
//dependency level 3
path lineD_C = (D-20.0*unit(C-D))--(C+20.0*unit(C-D));
//dependency level 4
pair P = intersectionpoint(lineB_A, lineD_C); dot(P, c000000); label("$P$", P, dir(84.11889062937553));
//dependency level 5
path segP_B = P--B; draw(segP_B, c000000);
path segP_C = P--C; draw(segP_C, c000000);
