if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-3";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

import olympiad;
size(4cm);
pair A=dir(110);
pair B=dir(210);
pair C=dir(-30),D,E,F,I;
I=incenter(A,B,C);
D=foot(I,B,C);
E=foot(I,C,A);
F=foot(I,A,B);
dot(A^^B^^C^^I^^D^^E^^F);
draw(incircle(A,B,C),blue);
draw(A--B--C--cycle);
draw(A--I--B);
draw(I--C,red);
draw(I--D,dotted);
draw(I--E,dotted);
draw(I--F,dotted);
label("A",A,dir(90));
label("B",B,dir(200));
label("C",C,dir(-20));
label("D",D,dir(-90));
label("E",E,dir(35));
label("F",F,dir(135));
label("I",I,dir(60));
