if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-37";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

import olympiad;
size(4cm);
pair A = dir(110);
pair B = dir(210);
pair C = dir(330);
pair I = incenter(A, B, C);
pair D,E,F;
D=foot(I,B,C);
E=foot(I,C,A);
F=foot(I,A,B);
draw(A--B--C--cycle);
draw(circle(I,length(I-foot(I,B,C))));
dot("$A$", A, dir(A));
dot("$B$", B, dir(190));
dot("$C$", C, dir(-10));
dot("$D$", D, dir(-90));
dot("$E$", E, dir(40));
dot("$F$", F, dir(155));
