if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-4";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

import olympiad;
size(5cm);
pair A=dir(110), B=dir(200), C=dir(-20), D,E,F,G;
G=(A+B+C)/3;
D=(B+C)/2;
E=(C+A)/2;
F=(A+B)/2;
dot(A^^B^^C^^D^^E^^F^^G);
draw(A--B--C--A);
draw(E--F);
draw(B--E);
draw(C--F);
label("A",A,N);
label("B",B,dir(190));
label("C",C,dir(-10));
label("D",D,S);
label("E",E,dir(45));
label("F",F,dir(140));
label("G",G,dir(90));
