if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-35";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

//Generated By AsyPadv1.2
import olympiad;
import markers;
import math;
import graph;
//change the unit size to fit your needs
size(6cm);
//colored pens
pen c000000 = rgb("000000");
//dependency level 0
/* You can change the coordinates of these points of dependency level 0.
The drawing will retain the same relationships and qualities.
Please be aware that as a result of this some of the image may be clipped off. */
pair B = (3.88, 17.20); dot(B, c000000); label("$B$", B, dir(51.60483549675433));
pair O = (3.19, 16.32);
//dependency level 1
//Do not change anything below, unless you are experienced in Asymptote.
path circO_B = Circle(O, abs(O-B));
pair circO_Bcenter = O; real circO_Brad = abs(O - B); draw(circO_B, c000000);
path segO_B = O--B;
//dependency level 2
pair C = relpoint(circO_B, -0.3326246702692839); dot(C, c000000); label("$C$", C, dir(253.50839790887915));
pair A = relpoint(circO_B, -0.6270403362062634); dot(A, c000000); label("$A$", A, dir(120.96189753921033));
path perB_segO_B = (B-20.0*(dir(segO_B).y, -dir(segO_B).x))--(B+20.0*(dir(segO_B).y, -dir(segO_B).x));
//dependency level 3
path segA_O = A--O;
path segA_B = A--B; draw(segA_B, c000000);
//dependency level 4
path perA_segA_O = (A-20.0*(dir(segA_O).y, -dir(segA_O).x))--(A+20.0*(dir(segA_O).y, -dir(segA_O).x));
//dependency level 5
pair P = intersectionpoint(perA_segA_O, perB_segO_B); dot(P, c000000); label("$P$", P, dir(88.28051995968144));
//dependency level 6
path segP_C = P--C; draw(segP_C, c000000);
path segP_A = P--A; draw(segP_A, c000000);
path segP_B = P--B; draw(segP_B, c000000);
//dependency level 7
pair X = intersectionpoints(segP_C, circO_B)[0]; dot(X, c000000); label("$X$", X, dir(129.2296640975739));
pair Y = intersectionpoint(segA_B, segP_C); dot(Y, c000000); label("$Y$", Y, dir(133.61835402638553));
//clip the drawing view
clip((0.0, 13.0)--(0.0, 20.0)--(10.0, 20.0)--(10.0, 13.0)--cycle);
