if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-50";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

import olympiad;
size(4cm);
pair A=dir(-20), B=dir(110), C=dir(200), D, E, F, G;
D=(B+C)/2;
E=(C+A)/2;
F=(A+B)/2;
G=(A+B+C)/3;
draw(A--B--C--A);
draw(A--D);
draw(B--E);
draw(C--F);
dot(A^^B^^C^^D^^E^^F^^G);
label("1",A,dir(-20));
label("1",C,dir(200));
label("1",B,dir(90));
label("2",D,dir(140));
label("2",E,dir(-80));
label("2",F,dir(40));
label("3",G,1.3dir(63));
