if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="preview-60";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

import olympiad;
size(6cm);
pair A = origin;
pair B = (4.75,0);
pair E1=(0,3);
pair F = (4.75,3);
pair G = (5.95,4.2);
pair C = (5.95,1.2);
pair D = (1.2,1.2);
pair H= (1.2,4.2);
pair M = ((4.75+5.95)/2,3.6);
draw(E1--M--H--E1--A--B--E1--F--B--M--C--G--H);
draw(B--C);
draw(F--G);
draw(A--D--H--C--D,dashed);
label("$A$",A,SW);
label("$B$",B,SE);
label("$C$",C,E);
label("$D$",D,W);
label("$E$",E1,W);
label("$F$",F,SW);
label("$G$",G,NE);
label("$H$",H,NW);
label("$M$",M,N);
dot(A);
dot(B);
dot(E1);
dot(F);
dot(G);
dot(C);
dot(D);
dot(H);
dot(M);
label("3",A/2+B/2,S);
label("2",C/2+G/2,E);
label("1",C/2+B/2,SE);
