if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
defaultfilename="meet1-3";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);

size(6cm);
import olympiad;
import cse5;
import geometry;

size(6cm);
label("$B$", (0,0), SW);
label("$O$", (1,0), S);
label("$A$", (2,0), SE);
label("$X$", (2.5,0), SE);
label("$M$", (0,sqrt(5)/2), W);
label("$Y$", (0,sqrt(5)), NW);
label("$T$", (5/3,sqrt(5)/3), NE);
dot((0,0));
dot((1,0));
dot((2,0));
dot((2.5,0));
dot((0,sqrt(5)/2));
dot((5/3,sqrt(5)/3));
dot((0,sqrt(5)));
draw((0,0)--(2.5,0)--(0,sqrt(5))--cycle);
draw(circle((1,0),1));
